# Generated by Django 5.0.7 on 2024-08-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_clubs_and_societies_alter_about_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='administrator',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
