# Generated by Django 5.0.7 on 2024-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_backgroundimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='role',
            field=models.CharField(blank=True, choices=[('Chief Principal', 'Chief Principal'), ('D/Admin', 'D/Admin'), ('D/Acad', 'D/Acad'), ('Dean', 'Dean'), ('HOD', 'HOD'), ('HOS', 'HOS')], max_length=100),
        ),
        migrations.AddField(
            model_name='administrator',
            name='subjects',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('Chief Principal', 'Chief Principal'), ('D/Admin', 'D/Admin'), ('D/Acad', 'D/Acad'), ('Dean', 'Dean'), ('HOD', 'HOD'), ('HOS', 'HOS')], max_length=100),
        ),
    ]
