# Generated by Django 5.0.7 on 2024-08-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.CharField(blank=True, choices=[('Chief Principal', 'Chief Principal'), ('D/Admin', 'D/Admin'), ('D/Acad', 'D/Acad'), ('Dean', 'Dean'), ('HOD MATHEMATICS', 'HOD MATHEMATICS'), ('HOD SCIENCE', 'HOD SCIENCE'), ('HOD ENGLISH', 'HOD ENGLISH'), ('HOD KISWAHILI', 'HOD KISWAHILI'), ('HOD HUMANITIES', 'HOD HUMANITIES'), ('HOD TECHNICALS', 'HOD TECHNICALS'), ('HOD G&C', 'HOD G&C'), ('HOD CAREERS', 'HOD CAREERS'), ('HOD SPORTS', 'HOD SPORTS'), ('HOS', 'HOS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='subjects',
            field=models.CharField(blank=True, choices=[('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('Chief Principal', 'Chief Principal'), ('D/Admin', 'D/Admin'), ('D/Acad', 'D/Acad'), ('Dean', 'Dean'), ('HOD MATHEMATICS', 'HOD MATHEMATICS'), ('HOD SCIENCE', 'HOD SCIENCE'), ('HOD ENGLISH', 'HOD ENGLISH'), ('HOD KISWAHILI', 'HOD KISWAHILI'), ('HOD HUMANITIES', 'HOD HUMANITIES'), ('HOD TECHNICALS', 'HOD TECHNICALS'), ('HOD G&C', 'HOD G&C'), ('HOD CAREERS', 'HOD CAREERS'), ('HOD SPORTS', 'HOD SPORTS'), ('HOS', 'HOS')], max_length=100),
        ),
    ]
