# Generated by Django 5.0.7 on 2024-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_administrator_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='subjects',
            new_name='subject1',
        ),
        migrations.AddField(
            model_name='administrator',
            name='subject2',
            field=models.CharField(blank=True, choices=[('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS')], max_length=200),
        ),
    ]
