# Generated by Django 5.0.7 on 2024-08-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_subjects_administrator_subject1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='subject2',
        ),
        migrations.AddField(
            model_name='administrator',
            name='subjects',
            field=models.CharField(blank=True, choices=[('BIO & CHEM', 'BIO & CHEM'), ('PHYS & CHEM', 'PHY & CHEM'), ('MATHS & PHY', 'MATH & PHY'), ('MATHS & CHEM', 'MATHS & CHEM'), ('HIS & CRE', 'HIS & CRE'), ('GEO & HIS', 'GEO & HIS'), ('HIS & KIS', 'HIS & KIS'), ('KIS & CRE', 'KIS & CRE'), ('ENG/LIT', 'ENG/LIT'), ('MATHS/COMP', 'MATHS/COMP'), ('MATHS/BUS', 'MATHS/BUS'), ('HSC/BIO', 'HSC/BIO'), ('MATH/GEO', 'MATH/GEO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='subjects',
            field=models.CharField(choices=[('BIO & CHEM', 'BIO & CHEM'), ('PHYS & CHEM', 'PHY & CHEM'), ('MATHS & PHY', 'MATH & PHY'), ('MATHS & CHEM', 'MATHS & CHEM'), ('HIS & CRE', 'HIS & CRE'), ('GEO & HIS', 'GEO & HIS'), ('HIS & KIS', 'HIS & KIS'), ('KIS & CRE', 'KIS & CRE'), ('ENG/LIT', 'ENG/LIT'), ('MATHS/COMP', 'MATHS/COMP'), ('MATHS/BUS', 'MATHS/BUS'), ('HSC/BIO', 'HSC/BIO'), ('MATH/GEO', 'MATH/GEO')], max_length=200),
        ),
    ]
