# Generated by Django 5.0.7 on 2024-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_administrator_subject1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='role',
            field=models.CharField(blank=True, choices=[('CHIEF PRINCIPAL', 'CHIEF PRINCIPAL'), ('DEPUTY PRINCIPAL(ADMIN)', 'DEPUTY PRINCIPAL(ADMIN)'), ('DEPUTY PRINCIPAL(ACAD)', 'DEPUTY PRINCIPAL(ACAD)'), ('DEAN', 'DEAN'), ('HOD MATHEMATICS', 'HOD MATHEMATICS'), ('HOD SCIENCE', 'HOD SCIENCE'), ('HOD ENGLISH', 'HOD ENGLISH'), ('HOD KISWAHILI', 'HOD KISWAHILI'), ('HOD HUMANITIES', 'HOD HUMANITIES'), ('HOD TECHNICALS', 'HOD TECHNICALS'), ('HOD G&C', 'HOD G&C'), ('HOD CAREERS', 'HOD CAREERS'), ('HOD SPORTS', 'HOD SPORTS'), ('HOS', 'HOS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('CHIEF PRINCIPAL', 'CHIEF PRINCIPAL'), ('DEPUTY PRINCIPAL(ADMIN)', 'DEPUTY PRINCIPAL(ADMIN)'), ('DEPUTY PRINCIPAL(ACAD)', 'DEPUTY PRINCIPAL(ACAD)'), ('DEAN', 'DEAN'), ('HOD MATHEMATICS', 'HOD MATHEMATICS'), ('HOD SCIENCE', 'HOD SCIENCE'), ('HOD ENGLISH', 'HOD ENGLISH'), ('HOD KISWAHILI', 'HOD KISWAHILI'), ('HOD HUMANITIES', 'HOD HUMANITIES'), ('HOD TECHNICALS', 'HOD TECHNICALS'), ('HOD G&C', 'HOD G&C'), ('HOD CAREERS', 'HOD CAREERS'), ('HOD SPORTS', 'HOD SPORTS'), ('HOS', 'HOS')], max_length=100),
        ),
    ]
