# Generated by Django 5.0.7 on 2024-08-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_administrator_role_alter_teachingstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='mynews',
            field=models.FileField(default='', upload_to='news_info/'),
            preserve_default=False,
        ),
    ]
