# Generated by Django 5.0.7 on 2024-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_holidayassignment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayassignment',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024, max_length=4),
        ),
        migrations.AlterField(
            model_name='holidayassignment',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, max_length=1),
        ),
    ]
