# Generated by Django 5.0.7 on 2024-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_news_mynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mynews',
            field=models.FileField(blank=True, null=True, upload_to='news_info/'),
        ),
    ]
