# Generated by Django 5.0.7 on 2024-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='clubs_and_societies',
            field=models.TextField(help_text='Enter each club/society on a new line'),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=models.TextField(help_text='Enter each point on a new line'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subjects_offered',
            field=models.TextField(help_text='Enter each subject on a new line'),
        ),
    ]
