# Generated by Django 5.0.7 on 2024-08-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_administrator_role_administrator_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='administrator',
            name='subjects',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
