# Generated by Django 5.0.7 on 2024-08-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_administrator_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayassignment',
            name='year',
            field=models.IntegerField(default=2024, max_length=4),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='subjects',
            field=models.CharField(blank=True, choices=[('BIO & CHEM', 'BIO & CHEM'), ('PHYS & CHEM', 'PHY & CHEM'), ('MATH & PHY', 'MATH & PHY'), ('MATH & CHEM', 'MATH & CHEM'), ('HIS & CRE', 'HIS & CRE'), ('GEO & HIS', 'GEO & HIS'), ('HIS & KIS', 'HIS & KIS'), ('KIS & CRE', 'KIS & CRE'), ('ENG/LIT', 'ENG/LIT'), ('MATH/COMP', 'MATH/COMP'), ('MATH/BUS', 'MATH/BUS'), ('HSC/BIO', 'HSC/BIO'), ('MATH/GEO', 'MATH/GEO'), ('HIS/P.E', 'HIS/P.E')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='subjects',
            field=models.CharField(choices=[('BIO & CHEM', 'BIO & CHEM'), ('PHYS & CHEM', 'PHY & CHEM'), ('MATH & PHY', 'MATH & PHY'), ('MATH & CHEM', 'MATH & CHEM'), ('HIS & CRE', 'HIS & CRE'), ('GEO & HIS', 'GEO & HIS'), ('HIS & KIS', 'HIS & KIS'), ('KIS & CRE', 'KIS & CRE'), ('ENG/LIT', 'ENG/LIT'), ('MATH/COMP', 'MATH/COMP'), ('MATH/BUS', 'MATH/BUS'), ('HSC/BIO', 'HSC/BIO'), ('MATH/GEO', 'MATH/GEO'), ('HIS/P.E', 'HIS/P.E')], max_length=200),
        ),
    ]
