# Generated by Django 5.0.7 on 2024-08-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_holidayassignment_year_alter_administrator_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayassignment',
            name='year',
        ),
    ]
