# Generated by Django 5.0.7 on 2024-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_holidayassignment_year_alter_holidayassignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayassignment',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='holidayassignment',
            name='title',
            field=models.CharField(choices=[('May Holiday', 'May Holiday'), ('August HOliday', 'August HOliday'), ('December Holiday', 'December Holiday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='holidayassignment',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024),
        ),
    ]
