# Generated by Django 5.0.7 on 2024-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_holidayassignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayassignment',
            name='subject',
            field=models.CharField(choices=[('MATHEMATICS', 'MATHEMATICS'), ('ENGLISH', 'ENGLISH'), ('KISWAHILI', 'KISWAHILI'), ('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('BUSINESS STUDIES', 'BUSINESS STUDIES'), ('COMPUTER STUDIES', 'COMPUTER STUDIES'), ('AGRICULTURE', 'AGRICULTURE'), ('HOME SCIENCE', 'HOME SCIENCE'), ('HISTORY', 'HISTORY'), ('GEOGRAPHY', 'GEOGRAPHY'), ('CRE', 'CRE')], max_length=20),
        ),
    ]
