# Generated by Django 5.0.7 on 2024-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_holidayassignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayassignment',
            name='author',
            field=models.CharField(default='ADMIN', max_length=15),
        ),
    ]
