# Generated by Django 5.0.7 on 2024-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_holidayassignment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayassignment',
            name='title',
            field=models.CharField(choices=[('April Holiday', 'April Holiday'), ('August Holiday', 'August Holiday'), ('December Holiday', 'December Holiday')], max_length=200),
        ),
    ]
