# Generated by Django 5.0.7 on 2024-08-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_holidayassignment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayassignment',
            name='author',
        ),
    ]
