# Generated by Django 5.0.7 on 2024-08-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_holidayassignment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayassignment',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026)], default=2024),
        ),
    ]
