# Generated by Django 5.0.7 on 2024-08-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_holidayassignment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mynews',
            field=models.FileField(null=True, upload_to='news_info/'),
        ),
    ]
